name: Python package CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with your desired Python version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements file

    - name: Run tests
      run: |
        pytest  # Or the command to run your tests
        
    - name: Build and install package
      run: |
        python setup.py sdist bdist_wheel
        pip install .

    - name: Run additional checks (optional)
      run: |
        # Add any additional checks or scripts here
        
    - name: Deploy to PyPI (if desired)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Customize as needed
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        python -m twine upload --repository pypi dist/*

